# Pandas
This document introduces how to use pandas.
When you want to find out *how to do sth*, refer to [pandas-API](https://pandas.pydata.org/docs/reference/index.html)

## Model
This section illustrate the basis of pandas.
Most info derived from [pandas-user-guide](https://pandas.pydata.org/docs/user_guide/index.html)

Especially, you may find most from:
* [Intro-to-data-structures](https://pandas.pydata.org/docs/user_guide/dsintro.html#)


In [83]:
# Customarily, we import as follows:
import numpy as np
import pandas as pd
# pandas has two main data structure
# * series
# * dataframe

In [84]:
# Series
# * 1-Dimensional Index-Labeled Array
# - Data can be npArrays, dicts,strings...
npData = np.random.randn(4)
npSeries = pd.Series(npData,list("abcd"))
print(npSeries)
# - index will be numbers when not specified
print(pd.Series(npData))

# * Series is ndarray-like
# - Convert Series to ndarray
print("Convert series to ndarray: ")
s2array = npSeries.to_numpy()
print(s2array)
# * Series is dict-like
# - use get to provide a default value when missing
print("Get value like dict: ")
print(npSeries.get("a",np.nan))
print(npSeries.get("h",np.nan))



a    0.130838
b   -1.845626
c   -0.139827
d   -0.332038
dtype: float64
0    0.130838
1   -1.845626
2   -0.139827
3   -0.332038
dtype: float64
Convert series to ndarray: 
[ 0.13083796 -1.84562586 -0.13982728 -0.33203848]
Get value like dict: 
0.13083795508396048
nan


In [85]:
# DataFrame
# * 2-dimensional labeled data structure with columns of potentially different types
d = {
  "one": pd.Series([1, 2, 3], index=list("abc")),
  "two": pd.Series([3, 2, 1], index=list("bcd"))
}
df = pd.DataFrame(d)
print("index will be the union of various series")
print(df)

print("You can also specify index(row label) and column manually")
print(pd.DataFrame(d,index=list("bcm"), columns=["one", "two", "three"]))

index will be the union of various series
   one  two
a  1.0  NaN
b  2.0  3.0
c  3.0  2.0
d  NaN  1.0
You can also specify index(row label) and column manually
   one  two three
b  2.0  3.0   NaN
c  3.0  2.0   NaN
m  NaN  NaN   NaN


In [86]:
# Manipulations
print("Select a column: ")
print(df['one'])
print("Select rows: ")
print(df.loc['a'])
print(df.iloc[0])

print("Add or Modify a column: ")
df['three'] = df['one'] * df['two']
df['four'] = 4
df['one_trunc'] = df["one"][:2]
print(df)

print("pop a column: ")
three = df.pop("three")
print(three)

print("delete a column")
del df["two"]

print(df)

# * You can also convert a dataframe into a ndarray
df2array = np.asarray(df)
print(df2array)

Select a column: 
a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64
Select rows: 
one    1.0
two    NaN
Name: a, dtype: float64
one    1.0
two    NaN
Name: a, dtype: float64
Add or Modify a column: 
   one  two  three  four  one_trunc
a  1.0  NaN    NaN     4        1.0
b  2.0  3.0    6.0     4        2.0
c  3.0  2.0    6.0     4        NaN
d  NaN  1.0    NaN     4        NaN
pop a column: 
a    NaN
b    6.0
c    6.0
d    NaN
Name: three, dtype: float64
delete a column
   one  four  one_trunc
a  1.0     4        1.0
b  2.0     4        2.0
c  3.0     4        NaN
d  NaN     4        NaN
[[ 1.  4.  1.]
 [ 2.  4.  2.]
 [ 3.  4. nan]
 [nan  4. nan]]


## Work with Excel
This Section introduces how to work with excel files.
Refer to [pandas-excel](https://pandas.pydata.org/docs/user_guide/io.html#excel-files) for more details.

Particularly, this section describes:
* How to **read from** and **write to** an excel file
* How to **view the data** in excel
* How to **manipulate data** in excel


In [87]:
import pandas as pd

In [88]:
# Read a excel file, df for "data frame"
df = pd.read_excel('pdIn.xlsx')
print(df)
# Some basic properties
print("Properties: ")
print("shape: ",df.shape)

   Id  Name  Salary
0   1  Adam    4000
1   2   Bob    3000
2   3  Coke    5000
3   4  Lisa    1500
4   5  Lucy    2500
5   6  Boss    2000
Properties: 
shape:  (6, 3)


In [89]:
# To inspect the data
select_col = df['Name']
print(select_col)

0    Adam
1     Bob
2    Coke
3    Lisa
4    Lucy
5    Boss
Name: Name, dtype: object


In [90]:
# Manipulate Data

# Do something on a specific colomn
print("Salary Mean: ",df['Salary'].mean())

# Sort and get the maximum or minimun
sortBySalary = df.sort_values(['Salary'],ascending=False)
print("Highest Salary: ")
print(sortBySalary.head(1))
print("Lowest Salary: ")
print(sortBySalary.tail(1))

df.describe() # list some info of the numeric colomns

# Add a column
df['NewSalary'] = \
  2 * df['Salary']
print("New Data Frame: ")
print(df)


Salary Mean:  3000.0
Highest Salary: 
   Id  Name  Salary
2   3  Coke    5000
Lowest Salary: 
   Id  Name  Salary
3   4  Lisa    1500
New Data Frame: 
   Id  Name  Salary  NewSalary
0   1  Adam    4000       8000
1   2   Bob    3000       6000
2   3  Coke    5000      10000
3   4  Lisa    1500       3000
4   5  Lucy    2500       5000
5   6  Boss    2000       4000


In [91]:
# Write to excel
df.to_excel("pdOut.xlsx")